import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:pranidoctor_user/l10n/app_localizations.dart';

import '../../../../routing/app_routes.dart';
import '../../data/batch_dto.dart';

class BatchCard extends StatelessWidget {
  const BatchCard({super.key, required this.batch});

  final AnimalBatch batch;

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Card(
      child: ListTile(
        leading: CircleAvatar(child: Text('${batch.animalCount}')),
        title: Text(batch.name),
        subtitle: Text(
          [
            if (batch.animalType != null) batch.animalType!,
            l10n.batchAnimalCount(batch.animalCount),
            if (batch.pendingSync) l10n.batchPendingSync,
          ].where((s) => s.isNotEmpty).join(' · '),
        ),
        trailing: batch.isAutoGenerated
            ? Chip(label: Text(l10n.batchAutoGroup))
            : batch.animalCount == 0
            ? Chip(label: Text(l10n.batchEmptyStatus))
            : const Icon(Icons.chevron_right),
        onTap: () => context.push(AppRoutes.batchDetail(batch.id)),
      ),
    );
  }
}
