enum BatchFilter { all, active, empty }

enum BatchSort { nameAsc, nameDesc, recentFirst, animalsDesc }

class AnimalBatch {
  const AnimalBatch({
    required this.id,
    required this.name,
    this.notes,
    this.animalType,
    this.location,
    this.animalIds = const [],
    this.movements = const [],
    this.active = true,
    this.pendingSync = false,
    this.lastSyncError,
    this.isAutoGenerated = false,
    required this.createdAt,
    required this.updatedAt,
    this.fromCache = false,
  });

  final String id;
  final String name;
  final String? notes;
  final String? animalType;
  final String? location;
  final List<String> animalIds;
  final List<BatchMovement> movements;
  final bool active;
  final bool pendingSync;
  final String? lastSyncError;
  final bool isAutoGenerated;
  final DateTime createdAt;
  final DateTime updatedAt;
  final bool fromCache;

  int get animalCount => animalIds.length;

  AnimalBatch copyWith({
    String? name,
    String? notes,
    String? animalType,
    String? location,
    List<String>? animalIds,
    List<BatchMovement>? movements,
    bool? active,
    bool? pendingSync,
    String? lastSyncError,
    bool? isAutoGenerated,
    DateTime? updatedAt,
    bool? fromCache,
  }) {
    return AnimalBatch(
      id: id,
      name: name ?? this.name,
      notes: notes ?? this.notes,
      animalType: animalType ?? this.animalType,
      location: location ?? this.location,
      animalIds: animalIds ?? this.animalIds,
      movements: movements ?? this.movements,
      active: active ?? this.active,
      pendingSync: pendingSync ?? this.pendingSync,
      lastSyncError: lastSyncError,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      fromCache: fromCache ?? this.fromCache,
    );
  }

  factory AnimalBatch.fromJson(
    Map<String, dynamic> json, {
    bool fromCache = false,
  }) {
    return AnimalBatch(
      id: json['id'] as String,
      name: json['name'] as String? ?? 'Group',
      notes: json['notes'] as String?,
      animalType: json['animalType'] as String?,
      location: json['location'] as String?,
      animalIds: (json['animalIds'] as List<dynamic>? ?? [])
          .map((e) => e.toString())
          .toList(),
      movements: (json['movements'] as List<dynamic>? ?? [])
          .whereType<Map<String, dynamic>>()
          .map(BatchMovement.fromJson)
          .toList(),
      active: json['active'] as bool? ?? true,
      pendingSync: json['pendingSync'] as bool? ?? false,
      lastSyncError: json['lastSyncError'] as String?,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      createdAt:
          DateTime.tryParse(json['createdAt'] as String? ?? '') ??
          DateTime.now(),
      updatedAt:
          DateTime.tryParse(json['updatedAt'] as String? ?? '') ??
          DateTime.now(),
      fromCache: fromCache,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    if (notes != null) 'notes': notes,
    if (animalType != null) 'animalType': animalType,
    if (location != null) 'location': location,
    'animalIds': animalIds,
    'movements': movements.map((m) => m.toJson()).toList(),
    'active': active,
    'pendingSync': pendingSync,
    if (lastSyncError != null) 'lastSyncError': lastSyncError,
    'isAutoGenerated': isAutoGenerated,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
  };
}

class BatchMovement {
  const BatchMovement({
    required this.id,
    required this.type,
    this.fromBatchId,
    this.toBatchId,
    this.animalIds = const [],
    this.notes,
    required this.at,
  });

  final String id;
  final String type;
  final String? fromBatchId;
  final String? toBatchId;
  final List<String> animalIds;
  final String? notes;
  final DateTime at;

  factory BatchMovement.fromJson(Map<String, dynamic> json) {
    return BatchMovement(
      id: json['id'] as String? ?? '',
      type: json['type'] as String? ?? 'MOVE',
      fromBatchId: json['fromBatchId'] as String?,
      toBatchId: json['toBatchId'] as String?,
      animalIds: (json['animalIds'] as List<dynamic>? ?? [])
          .map((e) => e.toString())
          .toList(),
      notes: json['notes'] as String?,
      at: DateTime.tryParse(json['at'] as String? ?? '') ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type,
    if (fromBatchId != null) 'fromBatchId': fromBatchId,
    if (toBatchId != null) 'toBatchId': toBatchId,
    'animalIds': animalIds,
    if (notes != null) 'notes': notes,
    'at': at.toIso8601String(),
  };
}

class BatchInput {
  const BatchInput({
    required this.name,
    this.notes,
    this.animalType,
    this.location,
    this.animalIds = const [],
  });

  final String name;
  final String? notes;
  final String? animalType;
  final String? location;
  final List<String> animalIds;

  Map<String, dynamic> toCreateJson() => {
    'name': name.trim(),
    if (notes != null && notes!.trim().isNotEmpty) 'notes': notes!.trim(),
    if (animalType != null && animalType!.isNotEmpty) 'animalType': animalType,
    if (location != null && location!.trim().isNotEmpty)
      'location': location!.trim(),
    'animalIds': animalIds,
  };

  Map<String, dynamic> toPatchJson() => {
    'name': name.trim(),
    if (notes != null) 'notes': notes!.trim(),
    if (animalType != null) 'animalType': animalType,
    if (location != null) 'location': location!.trim(),
    'animalIds': animalIds,
  };

  Map<String, dynamic> toDraftJson() => {
    'name': name,
    'notes': notes,
    'animalType': animalType,
    'location': location,
    'animalIds': animalIds,
  };

  factory BatchInput.fromDraftJson(Map<String, dynamic> json) {
    return BatchInput(
      name: json['name'] as String? ?? '',
      notes: json['notes'] as String?,
      animalType: json['animalType'] as String?,
      location: json['location'] as String?,
      animalIds: (json['animalIds'] as List<dynamic>? ?? [])
          .map((e) => e.toString())
          .toList(),
    );
  }
}

class BatchPageResult {
  const BatchPageResult({
    required this.batches,
    required this.total,
    required this.page,
    required this.pageSize,
    required this.hasMore,
    this.withAnimalsCount = 0,
    this.emptyCount = 0,
    this.pendingSyncCount = 0,
    this.fromCache = false,
  });

  final List<AnimalBatch> batches;
  final int total;
  final int page;
  final int pageSize;
  final bool hasMore;
  final int withAnimalsCount;
  final int emptyCount;
  final int pendingSyncCount;
  final bool fromCache;

  BatchPageResult copyWith({
    List<AnimalBatch>? batches,
    int? total,
    int? page,
    int? pageSize,
    bool? hasMore,
    int? withAnimalsCount,
    int? emptyCount,
    int? pendingSyncCount,
    bool? fromCache,
  }) {
    return BatchPageResult(
      batches: batches ?? this.batches,
      total: total ?? this.total,
      page: page ?? this.page,
      pageSize: pageSize ?? this.pageSize,
      hasMore: hasMore ?? this.hasMore,
      withAnimalsCount: withAnimalsCount ?? this.withAnimalsCount,
      emptyCount: emptyCount ?? this.emptyCount,
      pendingSyncCount: pendingSyncCount ?? this.pendingSyncCount,
      fromCache: fromCache ?? this.fromCache,
    );
  }
}

class BatchAnimalSummary {
  const BatchAnimalSummary({
    required this.id,
    required this.label,
    this.animalType,
  });

  final String id;
  final String label;
  final String? animalType;
}

class BatchDetail {
  const BatchDetail({
    required this.batch,
    required this.animals,
    this.fromCache = false,
  });

  final AnimalBatch batch;
  final List<BatchAnimalSummary> animals;
  final bool fromCache;
}

class BatchMoveInput {
  const BatchMoveInput({
    required this.fromBatchId,
    required this.toBatchId,
    required this.animalIds,
    this.notes,
  });

  final String fromBatchId;
  final String toBatchId;
  final List<String> animalIds;
  final String? notes;

  Map<String, dynamic> toJson() => {
    'fromBatchId': fromBatchId,
    'toBatchId': toBatchId,
    'animalIds': animalIds,
    if (notes != null && notes!.trim().isNotEmpty) 'notes': notes!.trim(),
  };
}

class BatchMergeInput {
  const BatchMergeInput({
    required this.sourceBatchId,
    required this.targetBatchId,
  });

  final String sourceBatchId;
  final String targetBatchId;

  Map<String, dynamic> toJson() => {
    'sourceBatchId': sourceBatchId,
    'targetBatchId': targetBatchId,
  };
}
